config/routes.rb
Rails.application.routes.draw do
  root 'user_accounts#index'

  resources :user_accounts, only: [:destroy, :new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user_account.rb
class UserAccount < ApplicationRecord
  validates :first_name, presence: true,length: {maximum: 50}
  validates :last_name, presence: true,length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                   length: {maximum: 100},
                   format: {with: VALID_EMAIL_REGEX}
  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 8}
  validates :password, confirmation: { case_sensitive: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/user_accounts_controller.rb
class UserAccountsController < ApplicationController
  def new
    @account = UserAccount.new
  end

  def create
    @account = UserAccount.new(account_params)
    if @account.save
      redirect_to user_accounts_path
    else
      render 'new'
    end
  end

  def destroy
    UserAccount.find_by(id: params[:id]).destroy
    redirect_to user_accounts_path
  end

  def index
    @accounts = UserAccount.all
  end



  private
    def account_params
      params.require(:user_account)
            .permit(:first_name, :last_name, :email, :password, :password_confirmation, :password_hint)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_account_helper.rb
module UserAccountHelper
end

app/views/layouts/_body.html.erb
  <body>
    <div class= "container-fluid">
      <div class = "logo">
        <%= link_to "StoreIt", root_path%>
      </div>
      <%= render 'layouts/sidebar'%>
      <%= render 'layouts/header'%>
      <div class = 'main-body'>
        <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>   
        <%= yield %>
      </div>
    </div>
  </body>

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error-explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ol>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ol>
  </div>
<% end %>

app/views/layouts/_head.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<div class = 'header'>
  <div class = 'header-flex'>
    <span class = header-link>
      <%= link_to "Index", root_path%>
    </span>
    <span class = header-link>
      <%= link_to "New Account", new_user_account_path %>
    </span>
  </div>
  <div class = "header-title">
    <%= yield :header_title%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UI MiniApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= render 'layouts/head' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <%= yield %>
  </body>
</html>

app/views/user_accounts/index.html.erb
<% content_for :header_title do %>
  Index
<% end %>

<% if @accounts.length < 1%>
  <%= button_to "Create New Account", new_user_account_path, method: :get%>
<% else %>

  <div class = 'account-index'>
    <% @accounts.each do |account| %>
      <div class = 'account'>
        <div class=  'account-info'>
          <span id = "first-name">
            First Name: <%= account.first_name%>
          </span>
          <span id = "last-name">
            Last Name: <%= account.last_name%>
          </span>
          <span id = "email">
            Email Address: <%= account.email%>
          </span>
        </div>
        <span id = "delete-link">
          <%= link_to "Delete Account", user_account_path(account), method: :delete, data: { confirm: "Are you sure?" }%>
        </span>
      </div>
    <% end %>
  </div>

<% end %>

app/views/user_accounts/new.html.erb
<% content_for :header_title do %>
  Create Account
<% end %>

<div class = 'form-custom'>
  <div class = 'form-instructions'>
    <span id = 'instruction-text'>
      To create your new account, please fill in the following information and then click "submit".
    </span>
  </div>
  <%= form_with(model: @account, local: true) do |f|%>
    <%= render 'layouts/error_messages', object: f.object %>
    <div class = 'form-div'>
      <%= f.text_field :first_name, placeholder: "First Name..."%>
    </div>

    <div class = 'form-div'>
      <%= f.text_field :last_name, placeholder: "Last Name..."%>
    </div>

    <div class = 'form-div'>
      <%= f.text_field :email, placeholder: "Email..."%>
    </div>

    <div class = 'form-div'>
      <%= f.password_field :password, placeholder: "Password..."%>
    </div>

    <div class = 'form-div'>
      <%= f.password_field :password_confirmation, placeholder: "Retype Password..."%>
    </div>

    <div class = 'form-div'>
      <%= f.text_field :password_hint, placeholder: "Password Hint..."%>
    </div>


    <div class = 'form-div'>
      <%= f.submit "Submit", class: "btn btn-primary"%>
    </div>
  <% end%>
</div>